### ISSUE TITLE
Can't open or close a chat

### ISSUE THREAD

**Issue by AwfulNewb** [revoltchat/revolt.chat#10]
### What happened?

Some guy sent me a DM and I think he removed me from his friendlist right after the message, and now it's like this forever. Can't delete the chat and can't see his message.
![Snapshot_2022-11-07_02-39-15](https://user-images.githubusercontent.com/109723888/200251518-b46b5e14-985b-4970-8b49-fef477c320b4.png)

**Comment by Rexogamer** [comment]
This issue should be moved to [the Revite repo](https://github.com/revoltchat/revite) - can you get the user's ID?

**Comment by AwfulNewb** [comment]
His nickname is UseNobaraLinux1.

**Comment by insertish** [comment]
Closing due to rewrite, https://github.com/revoltchat/frontend.
Also I'm almost certain this is a duplicate issue.
