### ISSUE TITLE
bug: Uploading a banner GIF crashes app

### ISSUE THREAD

**Issue by dylanh724** [revoltchat/revolt.chat#18]
### What happened?

1. Upload a GIF for your banner
2. Crash catch modal:

![image](https://github.com/revoltchat/revolt.chat/assets/8840024/5fb85faa-4297-4be2-aa77-54896dfa4db0)

**Comment by Rexogamer** [comment]
Wrong repo - also, this doesn't actually crash the app (you can click OK to dismiss the error), and the error message suggests there was an issue trying to upload the GIF itself.
