### ISSUE TITLE
This website app.revolt.chat/server/01F7ZSBSFHQ8TA81725KQCSDDP/channel/01F7ZSBSFHCAAJQ92ZGTY67HMN is currently offline. Cloudflare's Always Online™ shows a snapshot of this web page from the Internet Archive's Wayback Machine. To check for the live version, click Refresh.bug: 

### ISSUE THREAD

**Issue by ghost** [revoltchat/revolt.chat#19]
### What happened?

Revolt app crashed randomly on me showed up a cloudflare bad gateway error pleae contact cloudflare and have a look into this issue

**Comment by Rexogamer** [comment]
Closing - the attacks in question have ended, this is in the wrong repo and the author has deleted their account.
