### ISSUE TITLE
bug: Voice Permissions

### ISSUE THREAD

**Issue by sammaxis** [revoltchat/revolt.chat#21]
### What happened?

In 'Voice Settings' I am given a notification of 'You need to grant permission to access audio settings.'

When I select 'Grant permission' I am able to select microphone and speaker / headphones settings.

However, these settings do not stay, and if I enter a voice call, I cannot hear anything. The settings never stay corrected.

**Comment by Rexogamer** [comment]
Wrong repo; also, this is a known issue with Revite that will be fixed in the new client.

**Comment by Ko4shi** [comment]
so when is it fixed

**Comment by arturkuchynski** [comment]
devs said 3 years ago that they will rebuild the voice but it's 2024 already.

**Comment by cemozr** [comment]
I have same issue
