### ISSUE TITLE
bug: unable to delete emojis in servers

### ISSUE THREAD

**Issue by pinkjimrussiagirl** [revoltchat/revolt.chat#22]
### What happened?

i have accidentally added an emoji in my server with the wrong name, and now i cannot delete it, because when i click on delete nothing happens

what is supposed to happen is it is supposed to delete the emoji instead of having to delete the entire server just to get rid of a single emoji with the wrong name

also please add the ability to rename emojis so i don’t have to keep deleting them and adding them again

**Comment by Rexogamer** [comment]
Wrong repo - also, can you check your browser console for any errors? (press CTRL-Shift-I (or Command-Shift-I on a Mac), then select Console and try deleting an emoji with it open)

**Comment by pinkjimrussiagirl** [comment]
> Wrong repo - also, can you check your browser console for any errors? (press CTRL-Shift-I (or Command-Shift-I on a Mac), then select Console and try deleting an emoji with it open)

ok thx for telling me because i didn’t know where to post the bug, also speaking of emojis my emojis keep resetting to mutant remix every time i open the app (i have it set to twemoji because that’s my most favorite emoji font)

**Comment by Rexogamer** [comment]
That's a known issue that will be fixed in the new client.

**Comment by pinkjimrussiagirl** [comment]
> That's a known issue that will be fixed in the new client.

ok, also is there a way for me to change the shapes of the status icons using css, here is what i currently have in my css but i think it might not be right

```
/* Online */
:is(circle[Attributes Style])[style="fill: var(--status-online)"] {
    background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1 1'><circle fill='white' cx='0.5' cy='0.5' r='0.5'/></svg>");
    fill: hsl(139, 47.3%, 43.9%) !important;
}
/* Do not disturb */
:is(circle[Attributes Style])[style attribute="fill: var(--status-busy)"] {
    background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1 1'><mask id='m'><circle fill='white' cx='0.5' cy='0.5' r='0.5'/><rect fill='black' x='0.125' y='0.375' width='0.75' height='0.25' rx='0.125' ry='0.125'/></mask><rect fill='black' x='0' y='0' width='1' height='1' mask='url(%23m)'/></svg>");
    fill: hsl(359, 82.6%, 59.4%) !important;
}
/* Away */
:is(circle[Attributes Style])[style attribute="fill: var(--status-away)"] {
    background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1 1'><mask id='m'><circle fill='white' cx='0.5' cy='0.5' r='0.5'/><circle fill='black' cx='0.25' cy='0.25' r='0.375'/></mask><rect fill='black' x='0' y='0' width='1' height='1' mask='url(%23m)'/></svg>");
    fill: hsl(38, 95.7%, 54.1%) !important;
}
/* Streaming */
:is(circle[Attributes Style])[style attribute="fill: var(--status-streaming)"] {
    background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1 1'><mask id='m'><circle fill='white' cx='0.5' cy='0.5' r='0.5'/><polygon fill='black' points='0.35,0.25 0.78301275,0.5 0.35,0.75'/></mask><rect fill='black' x='0' y='0' width='1' height='1' mask='url(%23m)'/></svg>");
    fill: hsl(262, 46.8%, 39.8%) !important;
}
/* Offline */
:is(circle[Attributes Style])[style attribute="fill: var(--status-invisible)"] {
    background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1 1'><mask id='m'><circle fill='white' cx='0.5' cy='0.5' r='0.5'/><circle fill='black' cx='0.5' cy='0.5' r='0.25'/></mask><rect fill='black' x='0' y='0' width='1' height='1' mask='url(%23m)'/></svg>");
    fill: hsl(214, 9.9%, 50.4%) !important;
}
```

**Comment by Rexogamer** [comment]
I'm going to say this once: **slow down**. You've already asked about the status icon, and in that list you are asking about ***twenty nine*** features/tweaks, many of which have already been answered or are too vague to be useful.

**Comment by pinkjimrussiagirl** [comment]
> I'm going to say this once: **slow down**. You've already asked about the status icon, and in that list you are asking about _**twenty nine**_ features/tweaks, many of which have already been answered or are too vague to be useful.

which ones were too vague to be useful

**Comment by Rexogamer** [comment]
A lot of the resdesign related ones - for example, what exactly would you want to see from a redesign of the permissions settings menu?

**Comment by Rexogamer** [comment]
Please stop repeatedly posting unrelated requests in issues.

**Comment by pinkjimrussiagirl** [comment]
> Please stop repeatedly posting unrelated requests in issues.

ok i will stop, but i do wish customizable user tags would get added in the new client

**Comment by pinkjimrussiagirl** [comment]
> Wrong repo - also, can you check your browser console for any errors? (press CTRL-Shift-I (or Command-Shift-I on a Mac), then select Console and try deleting an emoji with it open)

which repo am i supposed to use for reporting bugs on mobile browser, also it doesn’t let me edit server channels on ios mobile browser

**Comment by Rexogamer** [comment]
This is an issue with Revite and should be in its repo; and again, please stop with the unrelated issues

**Comment by insertish** [comment]
Closing this out as per above.
