### ISSUE TITLE
bug: YOUR WEBSITE IS TRASH? IT GIVES ME INTERNAL ERROR EVERYTIME?!

### ISSUE THREAD

**Issue by SerrialError** [revoltchat/revolt.chat#23]
### What happened?

what do I do bro!?

**Comment by Rexogamer** [comment]
What are you doing that triggers this error?

**Comment by SerrialError** [comment]
Thank you for replying to this, you guys are a great team. I made this issue as a joke, but it was still an issue. I am impressed by how professional you guys are. I got the error whenever I made an account.
  
  
  
  
  
  
  

  
  
>

**Comment by Rexogamer** [comment]
Of course! We're happy to help :smile: 

Assuming this isn't an issue anymore?

**Comment by SerrialError** [comment]
Correct, thank you!
  
  
  
  
  
  
  

  
  
>
