### ISSUE TITLE
Visual issue when opening channels

### ISSUE THREAD

**Issue by aeristhy** [revoltchat/revolt.chat#3]
https://not-an-iplogger.com/SO79iSHU.gif

**Comment by Rexogamer** [comment]
Thanks for reporting this - however, this is the wrong repo; you'll usually want to send future bug reports to [the Revite repo](https://github.com/revoltchat/revite/issues). This issue should hopefully be transferred over soon.

**Comment by aeristhy** [comment]
My apalogize and thanks for pointing it out! I'll clos this issue and open another one there
