### ISSUE TITLE
feature request: RSS/ATOM/JSON feed

### ISSUE THREAD

**Issue by ghost** [revoltchat/revolt.chat#7]
### What do you want to see?

I like revolt. I like feeds. Revolt has a blog. I want to know when it gets updated. You can read blogs from a feed reader. Revolt + RSS/ATOM/JSON feed = ❤️

**Comment by insertish** [comment]
Closed by #28

**Comment by gBasil** [comment]
The URLs in the footer of the website (revolt.chat) respond with 404s:
- https://revolt.chat/api/feed?format=rss
- https://revolt.chat/api/feed?format=atom
- https://revolt.chat/api/feed?format=json

**Comment by insertish** [comment]
Forgot about the route conflict with /api, I've rewritten this as a app router handler.
New links are:
- https://revolt.chat/feed/rss
- https://revolt.chat/feed/atom
- https://revolt.chat/feed/json
